name: Update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
      env:
        API_KEY= ${{ secrets.API_KEY }}
        CHANNELID= ${{ secrets.CHANNELID }}
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name nelsoncode019
        git config user.email nelsonher019@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Readme actualizado"
        git push origin master
